version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: oxroot
      MYSQL_DATABASE: ox
      MYSQL_USER: oxuser
      MYSQL_PASSWORD: oxpass
    ports: ["3306:3306"]
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/src/infra/db/migrate.sql:/docker-entrypoint-initdb.d/01_migrate.sql:ro

  adminer:
    image: adminer:latest
    ports: ["8080:8080"]
    depends_on: [mysql]

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - server/.env
    environment:
      CLIENT_URL: ${CLIENT_URL:-http://localhost:5173}
      DATABASE_URL: ${DATABASE_URL:-mysql://oxuser:oxpass@mysql:3306/ox}
      SESSION_SECRET: ${SESSION_SECRET:-change_me}
    ports: ["4000:4000"]
    depends_on: [mysql]
    volumes:
      - ./server:/app/server
      - /app/server/node_modules

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      VITE_API_BASE: ${VITE_API_BASE:-http://localhost:4000}
    ports: ["5173:5173"]
    depends_on: [server]
    volumes:
      - ./web:/app/web
      - /app/web/node_modules

volumes:
  mysql_data:
